In [1]:
# Import Libreries
from pathlib import Path
import pandas as pd

# Project root directory
ROOT_DIR = Path.cwd().parent

# Raw Dataset 
DATASET_PATH = ROOT_DIR / "Datasets" / "row"

files = list(DATASET_PATH.glob("coin_*.csv"))

print("Number of CSV files found:", len(files))

for file in files:
    print(file.name)
print("\nCurrent Path", Path.cwd())

Number of CSV files found: 23
coin_Aave.csv
coin_BinanceCoin.csv
coin_Bitcoin.csv
coin_Cardano.csv
coin_ChainLink.csv
coin_Cosmos.csv
coin_CryptocomCoin.csv
coin_Dogecoin.csv
coin_EOS.csv
coin_Ethereum.csv
coin_Iota.csv
coin_Litecoin.csv
coin_Monero.csv
coin_NEM.csv
coin_Polkadot.csv
coin_Solana.csv
coin_Stellar.csv
coin_Tether.csv
coin_Tron.csv
coin_Uniswap.csv
coin_USDCoin.csv
coin_WrappedBitcoin.csv
coin_XRP.csv

Current Path C:\Python for DA\project 10 Cryptocurrency\Notebook

In [2]:
dataframes = []

for file in files:

    df = pd.read_csv(file)

    crypto_name = file.stem.replace("coin_", "")

    df["Crypto"] = crypto_name

    dataframes.append(df)

master_df = pd.concat(dataframes, ignore_index=True)

master_df.head()

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap,Crypto
0,1,Aave,AAVE,2020-10-05 23:59:59,55.112358,49.787900,52.675035,53.219243,0.000000e+00,8.912813e+07,Aave
1,2,Aave,AAVE,2020-10-06 23:59:59,53.402270,40.734578,53.291969,42.401599,5.830915e+05,7.101144e+07,Aave
2,3,Aave,AAVE,2020-10-07 23:59:59,42.408314,35.970690,42.399947,40.083976,6.828342e+05,6.713004e+07,Aave
3,4,Aave,AAVE,2020-10-08 23:59:59,44.902511,36.696057,39.885262,43.764463,1.658817e+06,2.202651e+08,Aave
4,5,Aave,AAVE,2020-10-09 23:59:59,47.569533,43.291776,43.764463,46.817744,8.155377e+05,2.356322e+08,Aave

In [3]:
print("Total rows:", len(master_df))
print("Total columns:", len(master_df.columns))
print("Number of cryptocurrencies:", master_df["Crypto"].nunique())

print("\nCryptocurrencies:")
print(master_df["Crypto"].unique())

print("\nColumns:")
print(master_df.columns.tolist())

Total rows: 37082
Total columns: 11
Number of cryptocurrencies: 23

Cryptocurrencies:
<ArrowStringArray>
[          'Aave',    'BinanceCoin',        'Bitcoin',        'Cardano',
      'ChainLink',         'Cosmos',  'CryptocomCoin',       'Dogecoin',
            'EOS',       'Ethereum',           'Iota',       'Litecoin',
         'Monero',            'NEM',       'Polkadot',         'Solana',
        'Stellar',         'Tether',           'Tron',        'Uniswap',
        'USDCoin', 'WrappedBitcoin',            'XRP']
Length: 23, dtype: str

Columns:
['SNo', 'Name', 'Symbol', 'Date', 'High', 'Low', 'Open', 'Close', 'Volume', 'Marketcap', 'Crypto']

In [4]:
# Convert Datetime data type
master_df["Date"] = pd.to_datetime(
    master_df["Date"],
    format="mixed"
)

# Sort by cryptocurrency and date
master_df = master_df.sort_values(
    by=["Crypto", "Date"]
).reset_index(drop=True)

master_df.head(10)

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap,Crypto
0,1,Aave,AAVE,2020-10-05 23:59:59,55.112358,49.787900,52.675035,53.219243,0.000000e+00,8.912813e+07,Aave
1,2,Aave,AAVE,2020-10-06 23:59:59,53.402270,40.734578,53.291969,42.401599,5.830915e+05,7.101144e+07,Aave
2,3,Aave,AAVE,2020-10-07 23:59:59,42.408314,35.970690,42.399947,40.083976,6.828342e+05,6.713004e+07,Aave
3,4,Aave,AAVE,2020-10-08 23:59:59,44.902511,36.696057,39.885262,43.764463,1.658817e+06,2.202651e+08,Aave
4,5,Aave,AAVE,2020-10-09 23:59:59,47.569533,43.291776,43.764463,46.817744,8.155377e+05,2.356322e+08,Aave
5,6,Aave,AAVE,2020-10-10 23:59:59,51.405655,46.703328,46.818146,49.133718,1.074627e+06,2.472884e+08,Aave
6,7,Aave,AAVE,2020-10-11 23:59:59,51.453374,48.716040,49.133130,49.660726,6.921506e+05,2.499408e+08,Aave
7,8,Aave,AAVE,2020-10-12 23:59:59,54.421418,48.754077,49.661573,52.238692,1.354836e+06,2.629157e+08,Aave
8,9,Aave,AAVE,2020-10-13 23:59:59,57.481904,49.598735,52.238392,51.124317,1.386221e+06,2.573071e+08,Aave
9,10,Aave,AAVE,2020-10-14 23:59:59,57.853946,49.629529,51.372899,51.316518,3.132405e+06,2.582744e+08,Aave

In [5]:
MERGED_DATASET = ROOT_DIR / "Datasets"  / "merged" / "crypto_master.csv"

master_df.to_csv(MERGED_DATASET, index=False)
print("Merged dataset saved successfully!")
print(MERGED_DATASET)

Merged dataset saved successfully!
C:\Python for DA\project 10 Cryptocurrency\Datasets\merged\crypto_master.csv